Landing page with Hero component
Pho3nixHun/drone-biotech pull request #8
Opened 2024-08-27 15:30 UTC by Bence7

2024-08-28 20:48 UTC, Bence7 reviewed
I dont know why I cant push

2024-08-29 12:58 UTC, Pho3nixHun requested changes

2024-08-29 12:58 UTC, Pho3nixHun commented on src/app/shared/components/hero/hero.component.spec.ts
> +      <h1 testH1>The future of irrigation is now</h1>
Using the the properties as selectors is not correct. Select by tags (h1, p, a, button), select by ids or selext by class. Those are the standards. Adding a custom prop is like hacking, as that prop does not exists in the type definition of the element.

2024-08-29 14:18 UTC, Pho3nixHun approved these changes

2024-08-29 14:18 UTC, merged